### ISSUE TITLE
add g_var_calc and r_var_calc to es computation

### ISSUE THREAD

**Issue by mikabr** [langcog/metalab-archive#44]

**Comment by mikabr** [comment]
@shotsuji I could use your help with this

**Comment by shotsuji** [comment]
Hi,
first of all a different issue but since it is connected to the var_calc issue I also post it here. Christina and I finally solved the miracle of the different formula for g_calc (1 - 3 / (4 \* sum(n_1, n_2, na.rm = TRUE) - 5)) vs. (1 - 3 / (4 \* sum(n_1, n_2, na.rm = TRUE) - 9)) - it's bc the general formula is (1-3/(4*df-1)). Thus, for between-subject designs where you have df = n_1+n_2-2 you end up with -9, and for within-subject design where df = n_1-1 you end up with -5. Voila. 
So I suggest dividing cases for g_calc by participant_design: within_one and within_two --> -5, between --> -9

So on to g_var_calc:
The VARIANCE (for the -5 case) would be (1 - 3 / (4 \* sum(n_1, n_2, na.rm = TRUE) - 5)) ^ 2 \* d_var_calc ^ 2 
(in words: the square of the correction factor \* the variance of d (thus, the se of d that we calculate right now squared)
The SE of this would be  sqrt((1 - 3 / (4 \* sum(n_1, n_2, na.rm = TRUE) - 5)) ^ 2 \* d_var_calc ^ 2)

And on to r_var_calc: Here I'm not at all an expert, but the simple formula is
r_var_calc = (1-r^2)^2/(n_1-1)
However, what I am not sure about is that I have read it can be better to convert r to Fisher's z scale. I will create a separate issue for that.  

@christinabergmann: Maybe we can go through the above tmr together quickly to make sure I didn't make errors?
