### ISSUE TITLE
custom moderators per dataset

### ISSUE THREAD

**Issue by mcfrank** [langcog/metalab-archive#54]

**Comment by mikabr** [comment]
This is a little trickier than I though -- I've got custom moderators specified in `datasets.json` and included in the `rma`, the difficulty is with incorporating into the plots, since they split/colour things by value for categorical moderators. With just `response_mode` and `exposure_phrase`, we had a combined `response_mode_exposure_phase` that just pasted the two together and got used if you selected both. So I guess we instead need logic that takes whatever set of categorical moderators you selected, adds a column that combines them, and then uses that as the split/colour variable.

**Comment by mcfrank** [comment]
This would actually be great as it would cut out some of the weird logic of
hiding plots for some moderators.

**Comment by mikabr** [comment]
I'm not sure what you mean, isn't the only plot-hiding logic hiding the scatterplot for longitudinal datasets? How do moderators affect that?
