### ISSUE TITLE
label advantage has spooky funnel plot

### ISSUE THREAD

**Issue by mcfrank** [langcog/metalab-archive#55]

**Comment by mcfrank** [comment]
look at the radial distribution of ES/SE in funnel plot. there is clearly a bug here but we don't know where.

**Comment by mllewis** [comment]
I actually don't think there is a bug here. The variance (and SE) is a function of two  things in the 'within_one' case: sample size (n_1) and effect size (d_calc).  Here is the formula:

 d_var_calc <- (2/n_1) + (d_calc ^ 2 / (4 \* n_1)

[There was actually an error in this formula in compute_es, which I fixed.]

This means that d_var_calc will vary systematically with d_calc, when n_1 is held constant. It turns out that n_1 only has one of several values in this dataset. In particular, the giant arc is where n = 12. Does this make sense?

**Comment by mcfrank** [comment]
Yes it does! Adding Brock to the thread to confirm.

**Comment by brockf** [comment]
Very cool - never thought of that. Thanks for investigating @mllewis .
