### ISSUE TITLE
Adding hierarchical dependencies to MAs

### ISSUE THREAD

**Issue by shotsuji** [langcog/metalab-archive#65]
Speaking or correlations..
another type of dependency we are not accounting for currently is the fact that some ES might be more similar to each other than others, because they come from the same lab/article/country etc.
I also briefly asked COS starts consulting about that and they thought taking that into account on some level would make sense.
The approach that might make most sense for us is to decide on the hierarchical factor that we think would account for most of such within-factor similarity and implement that into our formula for instance as suggested [here](http://www.metafor-project.org/doku.php/analyses:konstantopoulos2011)
I'd think article would be a level that would be easy to implement and very clear. Thoughts?

**Comment by christinabergmann** [comment]
@shotsuji and I added a report to the repo, it does look like adding at least a level for paper is very useful for estimations as well as moderator analyses. We chose InWordDB for now as example.  
(NB: Lab was removed as moderator from InWordDB somehow, it's in the spreadsheet, can you help, @mikabr?)

**Comment by mikabr** [comment]
Sorry I missed this request for help -- is the issue there's a column you want to be in the data? If you add an entry for it to the field spec, it'll get pulled in.

**Comment by mcfrank** [comment]
I think they want hierarchicalrandomeffect.Rmd to get rendered in the repo.
To get a new report in there, you add it to metadata/reports.yaml - I've
done that for this one.

Mike

**Comment by christinabergmann** [comment]
Just to follow up, the request for help was that I was missing a column in the InWordDB section called "Lab" that was supposed to help us check for lab-level random effects. I'm checking out how to add it, then we can try again. But to be clear, everything that's not in spec.yaml is removed from the individual datasets, right?

Then, it would be useful to add some way of accounting for dependencies on the paper (or maybe on the lab?) level to our computations, since there is quite some structure here. So we suggest to also change the way we compute ES and visualize to account for this. But that's of course something to discuss / investigate.
